name: mlflow-telco-churn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=23.0
  - pip:
      - mlflow>=2.10.0
      - scikit-learn>=1.3.0
      - pandas>=2.0.0
      - numpy>=1.24.0
      - matplotlib>=3.7.0
      - seaborn>=0.12.0
      - joblib>=1.3.0
      - scipy>=1.11.0