name: MLflow CI (Conda)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  train_with_conda:
    name: Run MLflow Project with Conda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9
          activate-environment: "churn-ci-env"

      - name: Install MLflow
        shell: bash -l {0}
        run: |
          pip install mlflow

      - name: Execute Training
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow run . --experiment-name Eksperimen_Churn_Prediction_Galih

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: training-results-conda
          path: MLProject/mlruns/
          retention-days: 5