name: ML Training Workflow

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Execute MLflow Project
        run: |
          cd MLProject
          mlflow run .